package com.togest.config;

public enum DataScope6CCode {
	
	//缺陷登记
	REGISTRATION_1C("LOOK_DEFECT_REGISTRATION_1C"), 
	REGISTRATION_2C("LOOK_DEFECT_REGISTRATION_2C"),
	REGISTRATION_3C("LOOK_DEFECT_REGISTRATION_3C"), 
	REGISTRATION_4C("LOOK_DEFECT_REGISTRATION_4C"), 
	REGISTRATION_5C("LOOK_DEFECT_REGISTRATION_5C"),
	
	//缺陷下达	
	LOOK_DEFECT_ISSUED_1C("LOOK_DEFECT_ISSUED_1C"),
	LOOK_DEFECT_ISSUED_2C("LOOK_DEFECT_ISSUED_2C"),
	LOOK_DEFECT_ISSUED_3C("LOOK_DEFECT_ISSUED_3C"),
	LOOK_DEFECT_ISSUED_4C("LOOK_DEFECT_ISSUED_4C"), 
	LOOK_DEFECT_ISSUED_5C("LOOK_DEFECT_ISSUED_5C"),
	
	//缺陷审核	
	AUDIT_1C("LOOK_DEFECT_AUDIT_1C"), 
	AUDIT_2C("LOOK_DEFECT_AUDIT_2C"),
	AUDIT_3C("LOOK_DEFECT_AUDIT_3C"), 
	AUDIT_4C("LOOK_DEFECT_AUDIT_4C"),
	AUDIT_5C("LOOK_DEFECT_AUDIT_5C"), 
	
	//车间接收	
	SHOP_RECEIVE_1C("LOOK_SHOP_RECEIVE_1C"), 
	SHOP_RECEIVE_2C("LOOK_SHOP_RECEIVE_2C"), 
	SHOP_RECEIVE_3C("LOOK_SHOP_RECEIVE_3C"),
	SHOP_RECEIVE_4C("LOOK_SHOP_RECEIVE_4C"), 
	SHOP_RECEIVE_5C("LOOK_SHOP_RECEIVE_5C"), 
	
	//复核整改	
	REVIEW_RECTIFICATION_1C("LOOK_REVIEW_RECTIFICATION_1C"), 
	REVIEW_RECTIFICATION_2C("LOOK_REVIEW_RECTIFICATION_2C"),
	REVIEW_RECTIFICATION_3C("LOOK_REVIEW_RECTIFICATION_3C"),
	REVIEW_RECTIFICATION_4C("LOOK_REVIEW_RECTIFICATION_4C"),
	REVIEW_RECTIFICATION_5C("LOOK_REVIEW_RECTIFICATION_5C"), 
	
	//延期审核	
	REFORM_AND_EXTENSION_1C("LOOK_REFORM_AND_EXTENSION_1C"),
	REFORM_AND_EXTENSION_2C("LOOK_REFORM_AND_EXTENSION_2C"),
	REFORM_AND_EXTENSION_3C("LOOK_REFORM_AND_EXTENSION_3C"),
	REFORM_AND_EXTENSION_4C("LOOK_REFORM_AND_EXTENSION_4C"),
	REFORM_AND_EXTENSION_5C("LOOK_REFORM_AND_EXTENSION_5C"),
	
	//整改验证	
	RECTIFICATION_VERIFICATION_1C("LOOK_RECTIFICATION_VERIFICATION_1C"),
	RECTIFICATION_VERIFICATION_2C("LOOK_RECTIFICATION_VERIFICATION_2C"),
	RECTIFICATION_VERIFICATION_3C("LOOK_RECTIFICATION_VERIFICATION_3C"),
	RECTIFICATION_VERIFICATION_4C("LOOK_RECTIFICATION_VERIFICATION_4C"),
	RECTIFICATION_VERIFICATION_5C("LOOK_RECTIFICATION_VERIFICATION_5C"), 
	
	//缺陷信息查看	
	DEFECT_INFORMATION_1C("DEFECT_INFORMATION_HANDLE_1C"), 
	DEFECT_INFORMATION_2C("DEFECT_INFORMATION_HANDLE_2C"), 
	DEFECT_INFORMATION_3C("DEFECT_INFORMATION_HANDLE_3C"), 
	DEFECT_INFORMATION_4C("DEFECT_INFORMATION_HANDLE_4C"),
	DEFECT_INFORMATION_5C("DEFECT_INFORMATION_HANDLE_5C"),
	
	//检测作业	
	LOOK_TESTING_TASK_1C("LOOK_TESTING_TASK_1C"),
	LOOK_TESTING_TASK_2C("LOOK_TESTING_TASK_2C"),
	LOOK_TESTING_TASK_4C("LOOK_TESTING_TASK_4C"),
	
	//监测点	
	LOOK_MONITORING_SEARCH_5C("LOOK_MONITORING_SEARCH_5C"),
	
	//历史缺陷	
	HISTORY_DEFECT("LOOK_HISTORY_DEFECTS_NEX");
	
	private final String status;

	DataScope6CCode(String status) {
		this.status = status;
	}

	public String getStatus() {
		return status;
	}

}
