CREATE TABLE `bd_a_power` (
  `id` varchar(50) NOT NULL COMMENT '编号',
  `line_id` varchar(50) DEFAULT NULL COMMENT '线路ID',
  `file_id` text COMMENT '附件ID',
  `pavilion_id` varchar(50) DEFAULT NULL COMMENT '变电所ID',
  `ps_pd_id` varchar(50) DEFAULT NULL COMMENT '供电臂ID',
  `sort` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `del_flag` smallint(1) DEFAULT '0',
  `create_ip` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `update_ip` varchar(50) DEFAULT NULL,
  `update_by` varchar(50) DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_ip` varchar(50) DEFAULT NULL,
  `delete_by` varchar(50) DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sort` (`sort`) USING BTREE,
  KEY `bd_a_power_line_pavilion_pspd` (`line_id`,`pavilion_id`,`ps_pd_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='越区供电方案';

CREATE TABLE `bd_construct_position` (
  `id` varchar(50) NOT NULL COMMENT '编号',
  `line_id` varchar(50) DEFAULT NULL COMMENT '线路ID',
  `file_id` text COMMENT '附件ID',
  `sort` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `del_flag` smallint(1) DEFAULT '0',
  `create_ip` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `update_ip` varchar(50) DEFAULT NULL,
  `update_by` varchar(50) DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_ip` varchar(50) DEFAULT NULL,
  `delete_by` varchar(50) DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sort` (`sort`) USING BTREE,
  KEY `bd_construct_postion_line` (`line_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='管内分相结构及分相位置';

CREATE TABLE `bd_corres_stand` (
  `id` varchar(50) NOT NULL COMMENT '编号',
  `line_id` varchar(50) DEFAULT NULL COMMENT '线路ID',
  `pavilion_id` varchar(50) DEFAULT NULL COMMENT '变电所ID',
  `ps_pd_id` varchar(50) DEFAULT NULL COMMENT '供电臂ID',
  `breaker_number` varchar(50) DEFAULT NULL COMMENT '断路器编号',
  `feeder_number` varchar(50) DEFAULT NULL COMMENT '馈线编号',
  `current_ratio` varchar(50) DEFAULT NULL COMMENT '电流比',
  `voltage_ratio` varchar(50) DEFAULT NULL COMMENT '电压比',
  `arm_length` varchar(50) DEFAULT NULL COMMENT '供电臂长度（公里）',
  `line_length` varchar(50) DEFAULT NULL COMMENT '供电线长度（公里）',
  `network_length` varchar(50) DEFAULT NULL COMMENT '接触网长度（公里）',
  `unit_power_line` varchar(50) DEFAULT NULL COMMENT '供电线单位电抗（Ω）',
  `unit_network_line` varchar(50) DEFAULT NULL COMMENT '接触网单位电抗（Ω）',
  `total_reactance1` varchar(50) DEFAULT NULL COMMENT 'Ⅰ段总电抗（Ω）',
  `total_reactance2` varchar(50) DEFAULT NULL COMMENT 'Ⅱ段总电抗（Ω）',
  `total_reactance3` varchar(50) DEFAULT NULL COMMENT 'Ⅲ段总电抗（Ω）',
  `sort` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `del_flag` smallint(1) DEFAULT '0',
  `create_ip` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `update_ip` varchar(50) DEFAULT NULL,
  `update_by` varchar(50) DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_ip` varchar(50) DEFAULT NULL,
  `delete_by` varchar(50) DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sort` (`sort`) USING BTREE,
  KEY `bd_corres_stand_line_pavilion_pspd` (`line_id`,`pavilion_id`,`ps_pd_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=349 DEFAULT CHARSET=utf8 COMMENT='故标对应';

CREATE TABLE `bd_corres_stand_detail` (
  `id` varchar(50) NOT NULL COMMENT '编号',
  `stand_id` varchar(50) DEFAULT NULL COMMENT '主表id',
  `psa_id` varchar(50) DEFAULT NULL COMMENT '区间或站场id',
  `psa_name` varchar(50) DEFAULT NULL COMMENT '站场名称',
  `pillar` varchar(50) DEFAULT NULL COMMENT '杆号',
  `glb` varchar(50) DEFAULT NULL COMMENT '公里标',
  `span` varchar(50) DEFAULT NULL COMMENT '跨距（m）',
  `distance` varchar(50) DEFAULT NULL COMMENT '距所距离（公里）',
  `iss_inductance` varchar(50) DEFAULT NULL COMMENT '电抗值',
  `note` varchar(50) DEFAULT NULL,
  `sort` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `del_flag` smallint(1) DEFAULT '0',
  `create_ip` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `update_ip` varchar(50) DEFAULT NULL,
  `update_by` varchar(50) DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_ip` varchar(50) DEFAULT NULL,
  `delete_by` varchar(50) DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sort` (`sort`) USING BTREE,
  KEY `bd_corres_stand_detail_stand` (`stand_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=153493 DEFAULT CHARSET=utf8 COMMENT='故标对应';

CREATE TABLE `bd_d_station` (
  `id` varchar(50) NOT NULL COMMENT '编号',
  `line_id` varchar(50) DEFAULT NULL COMMENT '线路ID',
  `file_id` text COMMENT '附件ID',
  `sort` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `del_flag` smallint(1) DEFAULT '0',
  `create_ip` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `update_ip` varchar(50) DEFAULT NULL,
  `update_by` varchar(50) DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_ip` varchar(50) DEFAULT NULL,
  `delete_by` varchar(50) DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sort` (`sort`) USING BTREE,
  KEY `bd_d_station_line` (`line_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=154 DEFAULT CHARSET=utf8 COMMENT='各线站细图';

CREATE TABLE `bd_emer_repair` (
  `id` varchar(50) NOT NULL COMMENT '编号',
  `name` text COMMENT '名称',
  `file_id` text COMMENT '附件ID',
  `sort` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `del_flag` smallint(1) DEFAULT '0',
  `create_ip` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `update_ip` varchar(50) DEFAULT NULL,
  `update_by` varchar(50) DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_ip` varchar(50) DEFAULT NULL,
  `delete_by` varchar(50) DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sort` (`sort`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=286 DEFAULT CHARSET=utf8 COMMENT='抢修预案';

CREATE TABLE `bd_fast_repaired` (
  `id` varchar(50) NOT NULL COMMENT '编号',
  `line_id` varchar(50) DEFAULT NULL COMMENT '线路',
  `file_id` text COMMENT '附件ID',
  `sort` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `del_flag` smallint(1) DEFAULT '0',
  `create_ip` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `update_ip` varchar(50) DEFAULT NULL,
  `update_by` varchar(50) DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_ip` varchar(50) DEFAULT NULL,
  `delete_by` varchar(50) DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sort` (`sort`) USING BTREE,
  KEY `bd_fast_repaired_line` (`line_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=166 DEFAULT CHARSET=utf8 COMMENT='抢修路径图';

CREATE TABLE `bd_line_bridge` (
  `id` varchar(50) NOT NULL COMMENT '编号',
  `line_id` varchar(50) DEFAULT NULL COMMENT '线路ID',
  `file_id` text COMMENT '附件ID',
  `sort` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `del_flag` smallint(1) DEFAULT '0',
  `create_ip` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `update_ip` varchar(50) DEFAULT NULL,
  `update_by` varchar(50) DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_ip` varchar(50) DEFAULT NULL,
  `delete_by` varchar(50) DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sort` (`sort`) USING BTREE,
  KEY `bd_line_bridge_line` (`line_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=340 DEFAULT CHARSET=utf8 COMMENT='上跨线、桥分布';

CREATE TABLE `bd_speed_limit` (
  `id` varchar(50) NOT NULL COMMENT '编号',
  `name` text COMMENT '名称',
  `file_id` text COMMENT '附件ID',
  `sort` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `del_flag` smallint(1) DEFAULT '0',
  `create_ip` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `update_ip` varchar(50) DEFAULT NULL,
  `update_by` varchar(50) DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_ip` varchar(50) DEFAULT NULL,
  `delete_by` varchar(50) DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sort` (`sort`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8 COMMENT='封锁、限速、降弓';

CREATE TABLE `bd_substation_range` (
  `id` varchar(50) NOT NULL COMMENT '编号',
  `line_id` varchar(50) DEFAULT NULL COMMENT '线路ID',
  `file_id` text COMMENT '附件ID',
  `pavilion_id` varchar(50) DEFAULT NULL COMMENT '变电所ID',
  `ps_pd_id` varchar(50) DEFAULT NULL COMMENT '供电臂ID',
  `start_glb` varchar(50) DEFAULT NULL COMMENT '公里标起点',
  `end_glb` varchar(50) DEFAULT NULL COMMENT '公里标终点',
  `power_supply_range` text COMMENT '供电范围',
  `sort` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `del_flag` smallint(1) DEFAULT '0',
  `create_ip` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `update_ip` varchar(50) DEFAULT NULL,
  `update_by` varchar(50) DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_ip` varchar(50) DEFAULT NULL,
  `delete_by` varchar(50) DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sort` (`sort`) USING BTREE,
  KEY `bd_substation_range_line_pavilion_pspd` (`line_id`,`pavilion_id`,`ps_pd_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=644 DEFAULT CHARSET=utf8 COMMENT='供电范围';

CREATE TABLE `bd_t_line` (
  `id` varchar(50) NOT NULL COMMENT '编号',
  `line_id` varchar(50) DEFAULT NULL COMMENT '线路ID',
  `pavilion_id` varchar(50) DEFAULT NULL COMMENT '变电所ID',
  `ps_pd_id` varchar(50) DEFAULT NULL COMMENT '供电臂ID',
  `tline_current` varchar(50) DEFAULT NULL COMMENT 'T线电流',
  `ct_ratio` varchar(20) DEFAULT '0' COMMENT 'CT变比',
  `pt_ratio` varchar(20) DEFAULT '0' COMMENT 'PT变比',
  `impedance_resistance` varchar(20) DEFAULT '0' COMMENT '阻抗I段电阻(二次值)',
  `sort` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `del_flag` smallint(1) DEFAULT '0',
  `create_ip` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `update_ip` varchar(50) DEFAULT NULL,
  `update_by` varchar(50) DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_ip` varchar(50) DEFAULT NULL,
  `delete_by` varchar(50) DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sort` (`sort`) USING BTREE,
  KEY `bd_t_line_line_pavilion_pspd` (`line_id`,`pavilion_id`,`ps_pd_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=268 DEFAULT CHARSET=utf8 COMMENT='供电臂T线电流标准';

CREATE TABLE `bd_trip_information` (
  `id` varchar(50) NOT NULL COMMENT '编号',
  `line_id` varchar(50) DEFAULT NULL COMMENT '线路ID',
  `pavilion_id` varchar(50) DEFAULT NULL COMMENT '变电所ID',
  `ps_pd_id` varchar(50) DEFAULT NULL COMMENT '供电臂ID',
  `time` varchar(50) DEFAULT NULL COMMENT '时间',
  `local_weather` text COMMENT '当地天气',
  `breaker_number` varchar(50) DEFAULT NULL COMMENT '断路器编号',
  `protect` varchar(30) DEFAULT NULL COMMENT '保护名称',
  `fault_type` varchar(30) DEFAULT NULL COMMENT '故障类型',
  `tline_voltage` varchar(50) DEFAULT NULL COMMENT 'T线电压（KV）',
  `fline_voltage` varchar(50) DEFAULT NULL COMMENT 'F线电压（KV）',
  `tline_current` varchar(50) DEFAULT NULL COMMENT 'T线电流（A）',
  `fline_current` varchar(50) DEFAULT NULL COMMENT 'F线电流（A）',
  `impedance_angle` varchar(50) DEFAULT NULL COMMENT '阻抗角（度）',
  `standard_distance` varchar(50) DEFAULT NULL COMMENT '故标距离',
  `coincidence_gate` varchar(30) DEFAULT NULL COMMENT '重合闸情况',
  `send_time` varchar(50) DEFAULT NULL COMMENT '复送时间',
  `arm_run_num` varchar(50) DEFAULT NULL COMMENT '供电臂内运行车辆数',
  `fline_influence` varchar(30) DEFAULT NULL COMMENT 'F线重合成功后了解动车组是否有异常',
  `fline_info` varchar(50) DEFAULT NULL COMMENT 'F线重合成功后影响行车信息',
  `foreign_infor` varchar(50) DEFAULT NULL COMMENT '外来信息',
  `jcw_fault_point` varchar(30) DEFAULT NULL COMMENT '接触网故障点',
  `speed_limit_requir` text COMMENT '通知行调限速要求',
  `direction` varchar(50) DEFAULT NULL COMMENT '行别',
  `power_cut_range` text COMMENT '停电范围',
  `kilo_distance` varchar(20) DEFAULT NULL,
  `mark` varchar(4) DEFAULT '0',
  `compose_voltage` varchar(50) DEFAULT '0' COMMENT '合成电压',
  `compose_current` varchar(50) DEFAULT '0' COMMENT '合成电流',
  `dz_resistance` varchar(50) DEFAULT '0' COMMENT '动作阻抗',
  `sort` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `del_flag` smallint(1) DEFAULT '0',
  `create_ip` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `update_ip` varchar(50) DEFAULT NULL,
  `update_by` varchar(50) DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_ip` varchar(50) DEFAULT NULL,
  `delete_by` varchar(50) DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sort` (`sort`) USING BTREE,
  KEY `bd_trip_information_line_pavilion_pspd` (`line_id`,`pavilion_id`,`ps_pd_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1418 DEFAULT CHARSET=utf8 COMMENT='牵引变电所跳闸信息';

CREATE TABLE `bd_trip_video_menu` (
  `id` varchar(50) NOT NULL COMMENT '编号',
  `line_id` varchar(50) DEFAULT NULL COMMENT '线路id',
  `psa_id` varchar(50) DEFAULT NULL COMMENT '区间站场id',
  `psa_name` varchar(50) DEFAULT NULL COMMENT '站区名称',
  `kind` varchar(255) DEFAULT NULL COMMENT '类别',
  `glb` varchar(50) DEFAULT NULL COMMENT '公里标',
  `distance` varchar(50) DEFAULT NULL COMMENT '间距',
  `mark` text COMMENT '备注（设备区域）',
  `sort` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `del_flag` smallint(1) DEFAULT '0',
  `create_ip` varchar(50) DEFAULT NULL,
  `create_by` varchar(50) DEFAULT NULL,
  `create_date` datetime DEFAULT NULL,
  `update_ip` varchar(50) DEFAULT NULL,
  `update_by` varchar(50) DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `delete_ip` varchar(50) DEFAULT NULL,
  `delete_by` varchar(50) DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sort` (`sort`) USING BTREE,
  KEY `bd_trip_video_menu_line` (`line_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=8493 DEFAULT CHARSET=utf8 COMMENT='段管内综合视频目录';
